# Generate Article Script
# Main entry point for article generation

param(
    [Parameter(Mandatory=$true)]
    [string]$Topic,
    
    [string]$OutputPath = "./output/article.md",
    [string]$ComplexityLevel = "medium"
)

$ErrorActionPreference = "Stop"

Write-Host "=== AI Article Writer ===" -ForegroundColor Cyan
Write-Host "Topic: $Topic" -ForegroundColor Yellow
Write-Host "Output: $OutputPath" -ForegroundColor Yellow
Write-Host "Complexity: $ComplexityLevel" -ForegroundColor Yellow

# Get script directory
$ScriptRoot = Split-Path -Parent $PSScriptRoot
$ToolRoot = Split-Path -Parent $ScriptRoot

# Check Node.js installation
if (-not (Get-Command node -ErrorAction SilentlyContinue)) {
    Write-Error "Node.js is required but not installed. Please install Node.js 18+ from https://nodejs.org/"
    exit 1
}

# Check for dependencies
$PackageJson = Join-Path $ToolRoot "package.json"
$NodeModules = Join-Path $ToolRoot "node_modules"

if (-not (Test-Path $NodeModules)) {
    Write-Host "`nDependencies not found. Installing..." -ForegroundColor Cyan
    Push-Location $ToolRoot
    npm install
    if ($LASTEXITCODE -ne 0) {
        Write-Error "Failed to install dependencies. Run 'npm install' manually."
        Pop-Location
        exit 1
    }
    Pop-Location
}

# Ensure output directory exists
$OutputDir = Split-Path -Parent $OutputPath
if (-not (Test-Path $OutputDir)) {
    New-Item -ItemType Directory -Path $OutputDir -Force | Out-Null
    Write-Host "Created output directory: $OutputDir" -ForegroundColor Green
}

# Run Node.js script
$NodeScript = Join-Path $ToolRoot "src\index.js"
if (-not (Test-Path $NodeScript)) {
    Write-Host "`nNode.js implementation not found. Creating placeholder article..." -ForegroundColor Yellow
    
    # Placeholder: Create a basic article structure
    $articleContent = @"
---
title: $Topic
complexity: $ComplexityLevel
generated: $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")
---

# $Topic

> This article was generated by AI Article Writer.
> Node.js implementation is in progress.

## Overview

This is a placeholder article for: **$Topic**

## Sections

Article sections will be generated here.

## Diagrams

Diagrams will be embedded here.

## Conclusion

Article conclusion will be generated here.
"@

    # Write placeholder article
    $articleContent | Out-File -FilePath $OutputPath -Encoding UTF8
    Write-Host "`nCreated placeholder article at: $OutputPath" -ForegroundColor Green
    Write-Host "`nNext steps: Implement Node.js script at src/index.js" -ForegroundColor Cyan
} else {
    # Run Node.js implementation
    Write-Host "`nRunning article generation..." -ForegroundColor Cyan
    Push-Location $ToolRoot
    node src/index.js --topic "$Topic" --output "$OutputPath" --complexity "$ComplexityLevel"
    $exitCode = $LASTEXITCODE
    Pop-Location
    
    if ($exitCode -ne 0) {
        Write-Error "Article generation failed with exit code $exitCode"
        exit $exitCode
    }
    
    Write-Host "`nArticle generated successfully at: $OutputPath" -ForegroundColor Green
}

Write-Host "`n=== Complete ===" -ForegroundColor Cyan

